# Generated by Django 4.2 on 2023-04-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
