# Generated by Django 4.2 on 2023-04-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0003_video_data_alter_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
