# Generated by Django 4.2 on 2023-04-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0006_video_total_score_gamescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
