name: Security Scan

on:
  pull_request_target:
  push:
    branches:
      - master

jobs:
  security_check:
    runs-on: ubuntu-latest
    permissions:
      security-events: write  # 允許上傳 SARIF
    steps:
      - name: 檢出代碼
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 取得最近的變更
        run: |
          git fetch origin master
          git diff -p HEAD~1 > changes.diff

      - name: 確保 security_report.sarif 是一個文件
        run: touch security_report.sarif

      - name: 拉取並運行 Docker 資安掃描
        env:
          OPEN_AI_KEY: ${{ secrets.OPEN_AI_KEY }}  # 使用 GitHub Secrets 傳遞密鑰
        run: |
          docker run --rm \
            -e OPEN_AI_KEY=$OPEN_AI_KEY \
            -v $(pwd)/changes.diff:/app/changes.diff \
            -v $(pwd)/security_report.sarif:/app/security_report.sarif \
            scottman625/my-security-scanner /app/changes.diff

      - name: 確保 SARIF 檔案正確
        run: |
          if [ ! -s security_report.sarif ]; then
            echo '{ "version": "2.1.0", "runs": [{ "tool": { "driver": { "name": "My Security Scanner", "version": "1.0.0" } }, "results": [] }] }' > security_report.sarif
          fi

      - name: 上傳 SARIF 報告作為 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: ./security_report.sarif

      - name: 上傳至 GitHub Security Alerts
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./security_report.sarif

