name: Security Scan

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  security_check:
    runs-on: ubuntu-latest
    steps:
      - name: 檢出代碼
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 取得最近的變更
        run: |
          git fetch origin master
          git diff -p HEAD~1 > changes.diff

      - name: 確保 security_report.sarif 是一個文件
        run: touch security_report.sarif

      - name: 拉取並運行 Docker 資安掃描
        run: |
          docker run --rm \
            -v $(pwd)/changes.diff:/app/changes.diff \
            -v $(pwd)/security_report.sarif:/app/security_report.sarif \
            scottman625/my-security-scanner /app/changes.diff

      - name: 上傳至 GitHub Security Alerts
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./security_report.sarif
